" Preamble --------------------------------------------------------------- {{{

filetype off
execute pathogen#infect()
filetype plugin indent on
set nocompatible

" }}}

" General Settings ------------------------------------------------------- {{{

set nobackup            " don't create backup files
set ruler               " display the cursor position
set nohlsearch          " don't highlight search terms
set bs=2                " allow useful backspace in insert mode

" set visible tab-width to 4 characters
set tabstop=4
set shiftwidth=4

" Enable fun indenting/functions
set nosi
set autoindent

" Color/style {{{
syntax on               " syntax highlighting is what the cool kids do
set bg=dark             " black terminal background
" support 256 color terminals
if &term =~ "xterm" || &term =~ "256color"
     set t_Co=256
endif
" Fix crappy Pmenu colors
hi Pmenu ctermfg=Gray
hi PmenuSel ctermfg=Gray

" }}}

" Folding {{{
"
" map space-bar to toggle folding
noremap <space> za

function! MyFoldText() " {{{
    let line = getline(v:foldstart)

    let nucolwidth = &fdc + &number * &numberwidth
    let windowwidth = winwidth(0) - nucolwidth - 3
    let foldedlinecount = v:foldend - v:foldstart

    " expand tabs into spaces
    let onetab = strpart('          ', 0, &tabstop)
    let line = substitute(line, '\t', onetab, 'g')

    let line = strpart(line, 0, windowwidth - 2 -len(foldedlinecount))
    let fillcharcount = windowwidth - len(line) - len(foldedlinecount)
    return line . '…' . repeat(" ",fillcharcount) . foldedlinecount . '…' . ' '
endfunction " }}}
set foldtext=MyFoldText()

" }}}

" }}}

" Filetype-specific ------------------------------------------------------ {{{

" Vim {{{

augroup ft_vim
	au!

	au FileType vim setlocal foldmethod=marker
	au FileType help setlocal textwidth=78
	au BufWinEnter *.txt if &ft == 'help' | wincmd L | endif
augroup END

" }}}

" }}}
