#!/bin/bash

# generate webrev and push to manta
name=$1
if [ -z "$name" ]; then
	echo 'usage: mwebrev <name>'
	exit 1
fi

if [ -e "$name" ]; then
	echo "webrev exists: $name"
	exit 1
fi

# No sense in continuing without manta keys
if ! ssh-add -l ; then
	exit 1
fi

webrev -o "$name"
tar cvf "$name.tar" "$name"
muntar -f "$name.tar" ~~/public/webrev
rm -r "$name" "$name.tar"

echo "WEBREV URL:"
echo "$MANTA_URL/$MANTA_USER/public/webrev/$name/index.html"
