#!/bin/bash
set -o vi
export EDITOR='vim'
export PAGER='less -d'
export HISTSIZE=50000

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias ll='ls -l'
alias grep='grep --color=auto'
alias tmat='tmux att -t'

# Fedora's default for this is stupidly verbose
unset PROMPT_COMMAND

function mantaenv() {
	if [ "$1" ]; then
		AGENT_KEY=$(ssh-add -l -E md5 | awk '
			$2 ~ /^MD5:/ {print substr($2, 5)}
			$2 ~ /^..:/ {print $2}
		')
		if [ "$AGENT_KEY" ]; then
			export MANTA_KEY_ID="$AGENT_KEY"
		else
			export MANTA_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
		fi

		export MANTA_USER=$1
		export MANTA_URL=https://us-east.manta.joyent.com
	fi
	if ! caller | grep -q profile; then
		env | grep MANTA
	fi
}

function sdcenv() {
	if [ "$1" ]; then
		case "$1" in
		'east')
			export SDC_URL='https://us-east-1.api.joyentcloud.com'
			;;
		'east3b')
			export SDC_URL='https://us-east-3b.api.joyentcloud.com'
			;;
		'west')
			export SDC_URL='https://us-west-1.api.joyentcloud.com'
			;;
		'sw')
			export SDC_URL='https://us-sw-1.api.joyentcloud.com'
			;;
		'ams')
			export SDC_URL='https://eu-ams-1.api.joyentcloud.com'
			;;
		*)
			export SDC_URL="https://$1"
		esac
		if [ "$2" ]; then
			export SDC_ACCOUNT=$2
		fi
		if [ "$3" ]; then
			export SDC_USER=$3
		else
			unset SDC_USER
		fi
		AGENT_KEY=$(ssh-add -l -E md5 | awk '
			$2 ~ /^MD5:/ {print substr($2, 5)}
			$2 ~ /^..:/ {print $2}
		')
		if [ "$AGENT_KEY" ]; then
			export SDC_KEY_ID="$AGENT_KEY"
		else
			export SDC_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
		fi
	fi
	if ! caller | grep -q profile; then
		env | grep SDC
	fi
}

function sshpub() {
	cat ~/.ssh/id_rsa.pub
	if [[ "$TMUX" ]]; then
		tmux set-buffer "$(cat ~/.ssh/id_rsa.pub)"
	fi
}

function pathinsertat() {
	export PATH=$(awk -v path="$PATH" -v ins="$1" -v at="$2" '
	BEGIN {
		n = split(path, parts, ":")
		out = ""
		for (i = n; i > 0; i--) {
			if (parts[i] == ins) {
				continue;
			}
			if (out == "") {
				out = parts[i];
			} else {
				out = parts[i] ":" out;
			}
			if (parts[i] == at && at != "") {
				out = ins ":" out;
				at = "";
			}
		}
		if (at != "") {
			out = ins ":" out;
		}
		print out;
	}
	')
}

# Cautiously update environment while inside tmux
function tmeu() {
	if [[ "$TMUX" ]]; then
		local EUPDATE=$(tmux show-environment | awk "
		BEGIN {
			envallow = \"DISPLAY SSH_AGENT_PID SSH_ASKPASS\" \\
			    \" SSH_AUTH_SOCK SSH_CONNECTION WINDOWID\" \\
			    \" XAUTHORITY WINDOWID\";
			split(envallow, parsed, \" \");
			for (n in parsed) {
				allow[parsed[n]] = n;
			}
		}
		/^-[A-Z_]/ {
			name = substr(\$1, 2);
			if (name in allow) {
				printf \"unset %s;\\n\", name;
				printf \"export %s;\\n\", name;
			}
		}
		/^[A-Z_]+=[-a-zA-Z0-9.\/ ]/ {
			mid = index(\$0, \"=\");
			name = substr(\$0, 1, mid-1);
			value = substr(\$0, mid+1);
			if (name in allow) {
				printf \"export %s='%s';\\n\", name, value;
			}
		}
		")
		echo "$EUPDATE"
		eval "$EUPDATE"
	fi
}

# OSX-specific configuration
if [ $(uname) = 'Darwin' ]; then
	# Colorize 'ls' and friends
	export CLICOLOR=1
	export PS1='\u@\h:\W\$ '
	BREW_PREFIX=$(brew --prefix)
	if [[ -d $BREW_PREFIX ]]; then
		source $BREW_PREFIX/etc/bash_completion
		alias git=$BREW_PREFIX/bin/git
		alias vim=$BREW_PREFIX/bin/vim
		alias ctags=$BREW_PREFIX/bin/ctags
	fi
	# Allow easy access to manta setup
	mantaenv patrick.mooney
	sdcenv west patrick.mooney

	# NVM setup
	source ~/.dotfiles/node/nvm/nvm.sh
	source ~/.dotfiles/node/nvm/bash_completion
fi

# Linux-specific configuration
if [ $(uname) = 'Linux' ]; then
	# Don't need slow/annoying apt-get suggestions
	unset command_not_found_handle

	# NVM setup
	source ~/.dotfiles/node/nvm/nvm.sh
	source ~/.dotfiles/node/nvm/bash_completion
fi

if [ $(uname) = 'SunOS' ]; then
	export PS1='[\u@\h \w]\$ '
	pathinsertat '/opt/local/bin' '/usr/bin'
	pathinsertat "$(readlink -f ~/.dotfiles/path/SunOS)" '/opt/local/bin'

	# Support color from GNU ls/grep
	if ls --help | grep -q color; then
		alias ls='\ls --color=auto'
	fi
	if grep --help | grep -q color; then
		alias grep='\grep --color=auto'
	fi

	# Allow easy access to manta setup
	if [ $SSH_AUTH_SOCK ]; then
		mantaenv patrick.mooney
	fi
fi
