#!/bin/bash
set -o vi
export EDITOR='vim'
export PAGER='less -d'
export HISTSIZE=50000

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias ll='ls -l'
alias grep='grep --color=auto'

# Fedora's default for this is stupidly verbose
unset PROMPT_COMMAND

function mantaenv() {
	if [ "$1" ]; then
		export MANTA_USER=$1
		export MANTA_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
		export MANTA_URL=https://us-east.manta.joyent.com
	fi
	if ! caller | grep -q profile; then
		env | grep MANTA
	fi
}

function sdcenv() {
	if [ "$1" ]; then
		case "$1" in
		'east')
			export SDC_URL='https://us-east-1.api.joyentcloud.com'
			;;
		'west')
			export SDC_URL='https://us-west-1.api.joyentcloud.com'
			;;
		'sw')
			export SDC_URL='https://us-sw-1.api.joyentcloud.com'
			;;
		'ams')
			export SDC_URL='https://eu-ams-1.api.joyentcloud.com'
			;;
		*)
			export SDC_URL="https://$1"
		esac
		if [ "$2" ]; then
			export SDC_ACCOUNT=$2
		fi
		if [ "$3" ]; then
			export SDC_USER=$3
		else
			unset SDC_USER
		fi
		export SDC_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
	fi
	if ! caller | grep -q profile; then
		env | grep SDC
	fi
}

function sshpub() {
	cat ~/.ssh/id_rsa.pub
	if [[ "$TMUX" ]]; then
		tmux set-buffer "$(cat ~/.ssh/id_rsa.pub)"
	fi
}

# OSX-specific configuration
if [ $(uname) = 'Darwin' ]; then
	# Colorize 'ls' and friends
	export CLICOLOR=1
	export PS1='\u@\h:\W\$ '
	BREW_PREFIX=$(brew --prefix)
	if [[ -d $BREW_PREFIX ]]; then
		source $(brew --prefix nvm)/nvm.sh
		source $BREW_PREFIX/etc/bash_completion
		alias git=$BREW_PREFIX/bin/git
		alias vim=$BREW_PREFIX/bin/vim
	fi
	# Allow easy access to manta setup
	mantaenv patrick.mooney
	sdcenv west patrick.mooney
fi

# Linux-specific configuration
if [ $(uname) = 'Linux' ]; then
	alias xkeys='~/.dotfiles/x11/xset.sh'
fi

if [ $(uname) = 'SunOS' ]; then
	export PS1='[\u@\h \w]\$ '
	export PATH="/opt/local/bin:$PATH"

	# Support color from GNU ls/grep
	if ls --help | grep -q color; then
		alias ls='\ls --color=auto'
	fi
	if grep --help | grep -q color; then
		alias grep='\grep --color=auto'
	fi
fi
