#!/bin/bash
set -o vi
export EDITOR='vim'
export PAGER='less -d'
export HISTSIZE=10000

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Work-related functions
alias dtterm='export TERM=dtterm'
# Easy detection for other configs about old vim/python/etc
export IS_RHEL6_HOST=`uname -r | awk -F- '{ if ($1 == "2.6.32") { print "YES" }}'`
alias ll='ls -l'

# Fedora's default for this is stupidly verbose
unset PROMPT_COMMAND

function mantaenv() {
	if [ "$1" ]; then
		export MANTA_USER=$1
		export MANTA_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
		export MANTA_URL=https://us-east.manta.joyent.com
	fi
	if ! caller | grep -q profile; then
		env | grep MANTA
	fi
}

function sdcenv() {
	if [ "$1" ]; then
		export SDC_ACCOUNT=$1
		if [ "$2" ]; then
			export SDC_USER=$2
		else
			unset SDC_USER
		fi
		export SDC_URL='http://localhost:8080'
		export SDC_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
	fi
	if ! caller | grep -q profile; then
		env | grep SDC
	fi
}

function sshpub() {
	cat ~/.ssh/id_rsa.pub
	if [[ "$TMUX" ]]; then
		tmux set-buffer "$(cat ~/.ssh/id_rsa.pub)"
	fi
}

# OSX-specific configuration
if [ $(uname) = 'Darwin' ]; then
	# Colorize 'ls' and friends
	export CLICOLOR=1
	export PS1='\u@\h:\W\$ '
	BREW_PREFIX=$(brew --prefix)
	if [[ -d $BREW_PREFIX ]]; then
		source $(brew --prefix nvm)/nvm.sh
		source $BREW_PREFIX/etc/bash_completion
		alias git=$BREW_PREFIX/bin/git
		alias vim=$BREW_PREFIX/bin/vim
	fi
	# Allow easy access to manta setup
	mantaenv patrick.mooney
	sdcenv patrick.mooney
fi
